import React from 'react';
import { motion, useAnimation } from 'framer-motion';
import { useEffect,useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const about = ({ textEnter, textLeave }) => {
  return (
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* Cursor  */}
      <div className={styles.videobackground}>
        
        <div className={styles.overlay}>
          <h2 onMouseEnter={textEnter} onMouseLeave={textLeave} id='about'>About Us</h2>
          <p onMouseEnter={textEnter} onMouseLeave={textLeave}>Welcome to DreamDose, your gateway to the hauntingly beautiful world of horror. <br />We are thrilled to have you join us on this journey into the unknown, <br /> where nightmares come alive, and the shadows tell tales that will send shivers down your spine.</p>
        </div>

        {/* <div className={styles.gola}></div> */}
      </div>
    </>
  );
};

export default about;
