import Head from 'next/head';
import { motion, useAnimation } from 'framer-motion';
import { useEffect,useState } from 'react';
import styles from '../styles/Home.module.css';
import Section from './section';
import { FaBars } from 'react-icons/fa';
import Blog from './blog';
import Contact from './contact';


const Home = ({ textEnter, textLeave }) => {
  const [menuVisible, setMenuVisible] = useState(false);
  const controls = useAnimation();

  useEffect(() => {
    controls.start({ y: 0, opacity: 1, transition: { duration: 1 } });
  }, [controls]);

  return (
    <>
      <Head>
        <title>DreamDose</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      
        {/*onMouseEnter={textEnter} onMouseLeave={textLeave} */}

        {/* Section Component  */}
        <Section textEnter={textEnter} textLeave={textLeave}/>

        {/* blog component  */}
        <Blog textEnter={textEnter} textLeave={textLeave}/>

        {/* Contact + Footer */}
        <Contact textEnter={textEnter} textLeave={textLeave}/>
        
      </main> 
    </>
  );
};

export default Home;
