import React from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import backimg from '../assets/sign.jpeg';
import Link from 'next/link';

const login = ({ textEnter, textLeave }) => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Add alt prop to the Image component */}
        <Image className={styles.imgsignup} src={backimg} alt="Background Image" />
      </div>
      <div className={styles.container} onMouseEnter={textEnter} onMouseLeave={textLeave}>
        <div className={styles.maincont}>
          <h2>Login</h2>
          <input type="email" placeholder="Email" />
          <input type="password" name="" id="" placeholder="Password" />
          <button type="button">
            {/* Wrap the Link around the button */}
            <Link href="/maindash" style={{ textDecoration: 'none', color: 'black' }}>
              Login
            </Link>
          </button>
          <p>
            Don't have an Account?{' '}
            <span>
              <Link href="/signup" style={{ color: 'white' }}>
                Signup
              </Link>
            </span>
          </p>
          <div className={styles.line}></div>
          <button type="button">
            {/* Wrap the Link around the button */}
            <Link href="/maindash" style={{ textDecoration: 'none', color: 'black' }}>
              Login with Google
            </Link>
          </button>
          <button type="button">
            {/* Wrap the Link around the button */}
            <Link href="/maindash" style={{ textDecoration: 'none', color: 'black' }}>
              Login with Facebook
            </Link>
          </button>
        </div>
      </div>
    </>
  );
};

export default login;
