import React, { useState } from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';
import Createblog from './Createblog';
import Manageblog from './Manageblog';

const Maindash = () => {
  const [activeComponent, setActiveComponent] = useState('create'); // 'create' or 'manage'

  const handleClick = (component) => {
    setActiveComponent(component);
  };

  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.maindash}>
        <div className={styles.sidebar}>
          <ul>
            <li onClick={() => handleClick('create')}>
              <Link href="">Create Blog</Link>
            </li>
            <br /><br />
            <li onClick={() => handleClick('manage')}>
              <Link href="">Manage Blog</Link>
            </li>
            <br /><br />
            
          </ul>
        </div>
        {activeComponent === 'create' && <Createblog />}
        {activeComponent === 'manage' && <Manageblog />}
      </div>
    </>
  );
};

export default Maindash;
