import React from 'react'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Image from 'next/image';
import backimg from "../assets/sign.jpeg"
import Link from 'next/link';

const signup = ({ textEnter, textLeave }) => {
  return (
    <>
    <Head>
        <title>Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <Image className={styles.imgsignup} src={backimg}/>
    </div>
    <div className={styles.container} onMouseEnter={textEnter} onMouseLeave={textLeave}>
    <div className={styles.maincont}>
        <h2>Signup</h2>
        <input type="email"  placeholder='Email'/>
        <input type="password" name="" id="" placeholder='Create password'/>
        <input type="password" name="" id="" placeholder='Confirm password'/>
        <button type="button"><Link href="/maindash" style={{textDecoration:"none" ,color:"black"}}>Signup</Link></button>
        <p>Already have an account? <span><Link href="/login" style={{color:"white"}}>Login</Link></span></p>
        <div className={styles.line}></div>
        <button type="button"><Link href="/maindash" style={{textDecoration:"none" ,color:"black"}}>Login with Google</Link></button>
        <button type="button"><Link href="/maindash" style={{textDecoration:"none" ,color:"black"}}>Login with Facebook</Link></button>
        </div>
    </div>
    </>
  )
}

export default signup